# Root file for the composition.

version: '2'

services:
  odoo:
    image: odoo:16.0
    command:
      --load-language fr_CH
    depends_on:
      - db
    ports:
      - 8080:8069  
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    volumes:
      - data-odoo:/var/lib/odoo
      - "./local-src:/mnt/extra-addons"
      - ./config:/etc/odoo
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5435:5440
    volumes:
      - data-db:/var/lib/postgresql/data/pgdata      

volumes:
  data-odoo:
  data-db: